### PR TITLE
fixed demo-dubbo balance or freeze_amount less than zero bug

### PR DESCRIPTION
**Pull request by WYUSIG**
Make sure that:

- [ ] You have read the [contribution guidelines](https://dromara.org/projects/hmily/contributor/).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by WYUSIG** [comment]
if AccountDTO#amount greater than database's balance and database's balance greater than zero, then database's balance will change to negative number, and will confirm

**Comment by WYUSIG** [comment]
if try step updates db's  table row == 0, should throw Exception, if not do that it will confirm

**Comment by yu199195** [comment]
pls check ci .

**Comment by WYUSIG** [comment]
my local test passed   mvn clean install -Dmaven.javadoc.skip=true , i don't know why github can't pass

**Review by yu199195 — APPROVED** [review]

**Pull request merged**
